services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-crud-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.26.3-alpine-slim
    container_name: crud-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: crud-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306